services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.axum
    container_name: app
    environment:
      APP__APPLICATION_PORT: ${APP__APPLICATION_PORT}
      APP__DATABASE__DATABASE_NAME: ${APP__DATABASE__DATABASE_NAME}
      APP__DATABASE__HOST: postgres
      APP__DATABASE__PORT: 5432
      APP__DATABASE__USERNAME: ${APP__DATABASE__USERNAME}
      APP__DATABASE__PASSWORD: ${APP__DATABASE__PASSWORD}
    depends_on:
      - postgres
    ports:
      - "${APP__APPLICATION_PORT}:${APP__APPLICATION_PORT}"
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${APP__DATABASE__USERNAME}
      POSTGRES_PASSWORD: ${APP__DATABASE__PASSWORD}
      POSTGRES_DB: ${APP__DATABASE__DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${APP__DATABASE__PORT}:5432"
    restart: unless-stopped

volumes:
  postgres_data:
